### ISSUE TITLE
Resolving alias with nextjs

### ISSUE THREAD

**Issue by hiddenLadder** [XantreGodlike/preact-signals#72] opened 2024-02-01 01:38 UTC
![image](https://github.com/XantreGodlike/preact-signals/assets/89526742/a25a8b00-ed05-463d-a927-7b0b2fc988ef)
How do we do that in NextJS (SWC plugin)?

**Comment by hiddenLadder** [comment] 2024-02-02 05:35
doesn't work 
![image](https://github.com/XantreGodlike/preact-signals/assets/89526742/b7bc05e6-ebb6-442c-bdf3-932922aae969)

**Comment by hiddenLadder** [comment] 2024-02-02 05:40
With turbopack
![image](https://github.com/XantreGodlike/preact-signals/assets/89526742/6ece06e8-bde5-4caa-b161-496c51b940ac)

**Comment by hiddenLadder** [comment] 2024-02-02 05:42
With turbopack
![image](https://github.com/XantreGodlike/preact-signals/assets/89526742/26dcce90-ad48-46b4-999b-a5106b2a0da8)

**Comment by XantreGodlike** [comment] 2024-02-02 08:31
Pls, check if it fixed an issue `transpilePackages: ['@preact-signals/unified-signals']`

**Comment by hiddenLadder** [comment] 2024-02-02 08:45
![image](https://github.com/XantreGodlike/preact-signals/assets/89526742/14ab134e-c97b-4f77-a780-0a6acdec3c04)

**Comment by XantreGodlike** [comment] 2024-02-02 09:54
Hah, interesting. This problem was caused by next.js resolving method. I will change the extension of transpiled files

**Comment by XantreGodlike** [comment] 2024-02-02 10:23
Pls, check with new versions #74

**Comment by XantreGodlike** [comment] 2024-02-02 11:54
![image](https://github.com/XantreGodlike/preact-signals/assets/57757211/d087be4c-fcb7-4bda-be6a-dd1688325149)

**Closed** 2024-02-05 16:59 UTC
Labels: documentation
